### ISSUE TITLE
Colors incorrectly set when swipe gesture ends

### ISSUE THREAD

**Issue by ndmeiri** [oscart/ODMSwipeSelector#4]
If the `swipingLabelColor` is set to a non-default value, the swipe label background does not retain that color when the swipe gesture ends. Instead, the swipe label background turns white.

**Comment by oscardemoya** [comment]
Hi @ndmeiri, Thanks, I've added the `originalBackgroundColor` to retain non-default background color. Also merged your PR to include the delegate methods for the value updates. This closes #1.
